name: wisehero-monitoring

volumes:
  # Prometheus 데이터 볼륨
  prometheus_data:
  # Grafana 데이터 볼륨
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' # 설정파일 경로 지정
      - '--storage.tsdb.path=/prometheus' # 시계열 데이터베이스 저장 경로 지정
    ports:
      - 9090:9090
    restart: unless-stopped # 수동 종료시를 제외한 상황에서 재시작
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus


networks:
  monitoring:
    driver: bridge