name: spring-app

services:
  spring-app:
    image: wisehero/spring-app:latest
    container_name: spring-app
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - monitoring