management:
  server:
    port: 8081
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: "health, info, prometheus"
      base-path: /my/actuator
